<?php
namespace app\admin\controller;

use app\admin\controller\Common;

use app\common\model\VyangAdminPush;
use OSS\Core\OssException;
use think\Db;
use think\Request;
use think\Loader;


/**
 *  话费管理
 * Class Puman
 * @package app\admin\controller
 */
class Huafei extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','21');
    }

    //列表
    public function huafei_order_list(){

        // 查询数据 并且每页显示10条数据
        $cont    = $this->request->get('cont');
        $type       = $this->request->get('type');
        $status     = $this->request->get('status');
        $lei     = $this->request->get('lei');

        $map    = [];
        $begintime     = $this->request->get('begintime',0);
        //申请时间 $begintime 2020-04-22 时间字符串
        if(!empty($begintime)){
            $time = strtotime($begintime);//开始时间
            $end_time = strtotime(date('Y-m-d 23:59:59',strtotime($begintime)));//结束时间
            $map['cz_huafei_user_order_time']      = ['between', [$time,$end_time]];
        }

        $page = '';
        if(!empty($type))
        {
            if($type == 1){
                $map['status']       = ['eq', 1];
            }
            if($type == 2){
                $map['status']       = ['eq', 2];
            }
            if($type == 3){
                $map['status']       = ['eq', 3];
            }
        }
        if(!empty($cont))
        {
            $cont_type    = $this->request->get('cont_type');
            if($cont_type == 1)
            {
                $map['cz_huafei_user_order_id']       = ['eq', $cont];
            }
            if($cont_type == 2)
            {
                $map['user_id']       = ['eq', $cont];
            }
            if($cont_type == 3)
            {
                $map['charge_phone']       = ['eq', $cont];
            }
        }

        $list   = PageSeach('cz_huafei_user_order', $map,[], 'cz_huafei_user_order_id desc', '1000', false, Request::instance()->param());

        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
            foreach ($list as $k => $v)
            {
                if(!empty($v['cz_huafei_user_order_time']))
                {
                    $list[$k]['cz_huafei_user_order_time']        = replaceTime($v['cz_huafei_user_order_time']);
                }else{
                    $list[$k]['cz_huafei_user_order_time']        = '';
                }
            }
        }

        if(!empty($list))
        {
            $list = _xss($list);
        }

        // 把分页数据赋值给模板变量list
        $this->assign('order',$list);
        $this->assign('show',$page);
        // 渲染模板输出

        return $this->fetch();
    }


    /**导出
     * @return null
     * @throws \PHPExcel_Exception
     * @throws \PHPExcel_Reader_Exception
     * @throws \PHPExcel_Writer_Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function out_huafei_list(){
        $piostdata = $this->request->post('arr/a',0);
        $path = '/filexlsx/'.md5(time().rand(100000,999999)).'.xlsx';
        $name = '列表';
        $title = [
            '序号',
            '用户ID',
            '账户',
            '金额',
            '订单号',
            '系统订单号',
            '下单时间',
            '状态',
            '名称',
            '通证',
            '完成时间',
            '余额',
        ];
        $url = 'http://'.$_SERVER['HTTP_HOST'].$path;
        $d = [];
        //查询
        $where['cz_huafei_user_order_id'] = ['in',implode(',',$piostdata)];
        $order_data = Db::name('cz_huafei_user_order')->where($where)->select();

        foreach ($order_data as $k => $v)
        {
            $d[$k]['序号'] = $v['cz_huafei_user_order_id'];
            $d[$k]['用户ID'] = $v['user_id'];
            $d[$k]['账户'] = $v['charge_phone']?$v['charge_phone']:'暂无';
            $d[$k]['金额'] = $v['charge_value']?$v['charge_value']:'无';
            $d[$k]['订单号'] = $v['ordersn'];
            $d[$k]['系统订单号'] = $v['order_id']?$v['order_id']:'无';
            $d[$k]['下单时间'] = replaceTime($v['cz_huafei_user_order_time']);

            $zhuangtai = '无';
            if($v['status'] == 1){$zhuangtai = '成功';}
            if($v['status'] == 2){$zhuangtai = '处理中';}
            if($v['status'] == 3){$zhuangtai = '失败';}
            if($v['status'] == 4){$zhuangtai = '未处理';}
            $d[$k]['状态'] = $zhuangtai;
            $d[$k]['名称'] = $v['product_name']?$v['product_name']:'无';
            $d[$k]['通证'] = $v['price_tongzheng']?$v['price_tongzheng']:'无';
            $d[$k]['完成时间'] = $v['charge_finish_time']?replaceTime($v['charge_finish_time']):'无';
            $d[$k]['余额'] = $v['balance']?$v['balance']:'没有查询余额';
        }

        $data = $d;
        $odata = wps($name,$title,$data,ROOT_PATH.'/public'.$path);

        if($odata){
            //return jsonSuccess(200,"<a href='". $url ."'>点击立即下载</a>  ".$url,['url' =>$url ]);
            return jsonSuccess(200,"<a href='". $url ."'>点击立即下载</a>  ");
        }else{
            return jsonError(500,'当前人数太多，处理失败，请稍后再试','');
        }
    }

    public function huafei_sub(){
        $id = $this->request->post('id',0);
        if(empty($id)){
            ajaxError('没有id');
        }

        $update = [];

        $r =  Db::name('cz_huafei_user_order')->where('cz_huafei_user_order_id',$id)->find();
        if(empty($r)){
            ajaxError('没有该订单');
        }

        if($r['status'] != 2){
            ajaxError('只能处理充值中的');
        }else{
            if(!empty($r['order_id'])){
                ajaxError('只能处理没有系统订单号的');
            }
        }

        $update['status'] = 3;

        $res =  Db::name('cz_huafei_user_order')->where('cz_huafei_user_order_id',$id)->update($update);
        if($res)
        {
                //退钱
                //整理人
                $info =[
                    'user_id'   => $r['user_id'],
                    'num'       => $r['price_tongzheng'],
                    'desc'      => '话费退款',
                    'type'      => '3',
                    'key'       => config('key'),    //key
                ];
                $url = 'http://127.0.0.1:9510/system/add_gold_integral_dian';
                VyangAdminPush::https_post($url, $info);

            ajaxSuccess('操作成功');
        }else{
            ajaxError('修改失败');
        }
    }
}

