<?php
namespace app\admin\controller;

use app\common\model\VyangAdminPush;
use think\Db;
use think\Request;
use app\admin\model\Common as adminModelCommon;

/**
 * 交易
 * Class JiaoYi
 * @package app\admin\controller
 */
class JiaoYi extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','16');
    }
    /**
     * 订单页面
     * @return mixed
     */
    public function jiaoyi_tz()
    {
        // 查询数据 并且每页显示10条数据
        $cont    = $this->request->get('cont');
        $type       = $this->request->get('type');
        $paixu     = $this->request->get('paixu');

        $map    = [];
        $page = '';
        if(!empty($cont))
        {
            $cont_type    = $this->request->get('cont_type');
            if($cont_type == 1)
            {
                if(isMobile($cont))
                {
                    $map['user_id']     = ['eq', Db::name('user')->where('mobile',$cont)->value('user_id') ];
                }else{
                    $map['user_id']     = ['eq', $cont];
                }
            }elseif ($cont_type == 2)
            {
                if(isMobile($cont))
                {
                    $map['to_id']     = ['eq', Db::name('user')->where('mobile',$cont)->value('user_id') ];
                }else{
                    $map['to_id']     = ['eq', $cont];
                }
            }elseif ($cont_type == 3)
            {
                $map['order_sn']    = ['eq', $cont];
            }
        }
        if(!empty($type))
        {
            $map['type']       = ['eq', $type];
        }

        $order = 'jiaoyi_tz_id desc';
        if($paixu)
        {
            switch ($paixu)
            {
                case '1':
                    $order = 'tz_num desc';
                    break;
                case '2':
                    $order = 'pm_num desc';
                    break;
            }
        }
        $list   = PageSeach('jiaoyi_tz', $map,[], $order, '10', false, Request::instance()->param());
        $type   = ['1'=>'上架中','3'=>'已取消','4'=>'已完成'];
        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
            foreach ($list as $k => $v)
            {
                $list[$k]['user_mobile']    = Db::name('user')->where('user_id',$v['user_id'])->value('mobile');
                $list[$k]['to_mobile']    = Db::name('user')->where('user_id',$v['to_id'])->value('mobile');
                $list[$k]['types']           = $type[$v['type']];
                $list[$k]['time']            = replaceTime($v['time']);
                $list[$k]['ok_time']            = replaceTime($v['ok_time']);
                $list[$k]['off_time']            = replaceTime($v['off_time']);
                if($v['off_time'] > 0)
                {
                    $list[$k]['off_time']        = replaceTime($v['off_time']);
                }else{
                    $list[$k]['off_time']   = '';
                }
                if($v['ok_time'] > 0)
                {
                    $list[$k]['ok_time']        = replaceTime($v['ok_time']);
                }else{
                    $list[$k]['ok_time']   = '';
                }
            }
        }
        if(!empty($list))
        {
            $list = _xss($list);
        }
        // 把分页数据赋值给模板变量list
        $this->assign('order',$list);
        $this->assign('type',$type);
        $this->assign('show',$page);
        $paixu = [
            '1' => '通证倒序',
            '2' => '扑满倒序',
        ];
        $this->assign('paixu', $paixu);
        // 渲染模板输出
        return $this->fetch();
    }

    /**
     * 取消订单
     */
    public function jiaoyi_quxiao()
    {
        $id = $this->request->post('id');
        $type = $this->request->post('type',0);
        $info =[
            'id'     => $id,
            'type'   => $type,
            'key'    => config('key'),    //key
        ];
        $url = 'http://127.0.0.1:9510/system/order';
        VyangAdminPush::https_post($url, $info);
        ajaxSuccess('操作成功');
    }

    /**
     * 订单页面
     * @return mixed
     */
    public function jiaoyi_pm()
    {
        // 查询数据 并且每页显示10条数据
        $cont    = $this->request->get('cont');
        $type       = $this->request->get('type');
        $paixu     = $this->request->get('paixu');

        $map    = [];
        $page = '';
        if(!empty($cont))
        {
            $cont_type    = $this->request->get('cont_type');
            if($cont_type == 1)
            {
                if(isMobile($cont))
                {
                    $map['user_id']     = ['eq', Db::name('user')->where('mobile',$cont)->value('user_id') ];
                }else{
                    $map['user_id']     = ['eq', $cont];
                }
            }elseif ($cont_type == 2)
            {
                if(isMobile($cont))
                {
                    $map['to_id']     = ['eq', Db::name('user')->where('mobile',$cont)->value('user_id') ];
                }else{
                    $map['to_id']     = ['eq', $cont];
                }
            }elseif ($cont_type == 3)
            {
                $map['order_sn']    = ['eq', $cont];
            }
        }
        if(!empty($type))
        {
            $map['type']       = ['eq', $type];
        }

        $order = 'jiaoyi_pm_id desc';
        if($paixu)
        {
            switch ($paixu)
            {
                case '1':
                    $order = 'tz_num desc';
                    break;
                case '2':
                    $order = 'pm_num desc';
                    break;
            }
        }
        $list   = PageSeach('jiaoyi_pm', $map,[], $order, '10', false, Request::instance()->param());
        $type   = ['1'=>'上架中','3'=>'已取消','4'=>'已完成'];
        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
            foreach ($list as $k => $v)
            {
                $list[$k]['user_mobile']    = Db::name('user')->where('user_id',$v['user_id'])->value('mobile');
                $list[$k]['to_mobile']    = Db::name('user')->where('user_id',$v['to_id'])->value('mobile');
                $list[$k]['types']           = $type[$v['type']];
                $list[$k]['time']            = replaceTime($v['time']);
                $list[$k]['ok_time']            = replaceTime($v['ok_time']);
                $list[$k]['off_time']            = replaceTime($v['off_time']);
                if($v['off_time'] > 0)
                {
                    $list[$k]['off_time']        = replaceTime($v['off_time']);
                }else{
                    $list[$k]['off_time']   = '';
                }
                if($v['ok_time'] > 0)
                {
                    $list[$k]['ok_time']        = replaceTime($v['ok_time']);
                }else{
                    $list[$k]['ok_time']   = '';
                }
            }
        }
        if(!empty($list))
        {
            $list = _xss($list);
        }
        // 把分页数据赋值给模板变量list
        $this->assign('order',$list);
        $this->assign('type',$type);
        $this->assign('show',$page);
        $paixu = [
            '1' => '通证倒序',
            '2' => '扑满倒序',
        ];
        $this->assign('paixu', $paixu);
        // 渲染模板输出
        return $this->fetch();
    }

}
