<?php
namespace app\admin\controller;

use app\common\model\VyangAdminPush;
use think\Db;
use think\Request;
use app\admin\model\Common as adminModelCommon;

/**
 * 订单
 * Class Cash
 * @package app\admin\controller
 */
class Order extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','5');
    }
    /**
     * 订单页面
     * @return mixed
     */
    public function order()
    {
        // 查询数据 并且每页显示10条数据
        $cont    = $this->request->get('cont');
        $type       = $this->request->get('type');
        $status     = $this->request->get('status');
        $lei     = $this->request->get('lei');

        $map    = [];
        $page = '';

        $begintime     = $this->request->get('begintime',0);
        //申请时间 $begintime 2020-04-22 时间字符串
        if(!empty($begintime)){
            $time = strtotime($begintime);//开始时间
            $end_time = strtotime(date('Y-m-d 23:59:59',strtotime($begintime)));//结束时间
            $map['pay_time']      = ['between', [$time,$end_time]];
        }

        if(!empty($cont))
        {
            $cont_type    = $this->request->get('cont_type');
            if($cont_type == 1)
            {
                $map['user_id']       = ['eq', $cont];
            }elseif ($cont_type == 2)
            {
                $map['order_sn']       = ['eq', $cont];
            }
        }
        if(!empty($type))
        {
            $map['payment_type']       = ['eq', $type];
        }
        if(!empty($lei))
        {
            $map['order_type']       = ['eq', $lei];
        }
        if(!empty($status))
        {
            $status = $status -1;
            $map['order_status']       = ['eq', $status];
        }
        $list   = PageSeach('order', $map,[], 'order_id desc', '1000', false, Request::instance()->param());
        $type   = ['1'=>'支付宝','2'=>'微信',3 => '银行卡',4=> '通证',5=> '扑满',6=> '其他'];
        $status = ['0'=>'未支付','1'=>'已支付'];
        $lei    = [1=>'实名认证支付',2=>'开通会员',3=> '续费会员',4=>'购买商品',5=>'通证申购',6=>'公益',7=>'其他'];
        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
            foreach ($list as $k => $v)
            {
                $list[$k]['types']           = $type[$v['payment_type']];
                $list[$k]['order_typee']           = $lei[$v['order_type']];
                $list[$k]['statuss']     = $status[$v['order_status']];
                $list[$k]['add_time']            = replaceTime($v['add_time']);
                if(!empty($v['pay_time']))
                {
                    $list[$k]['pay_time']        = replaceTime($v['pay_time']);
                }else{
                    $list[$k]['pay_time']        = '';
                }
            }
        }
        if(!empty($list))
        {
            $list = _xss($list);
        }
        // 把分页数据赋值给模板变量list
        $this->assign('order',$list);
        $this->assign('type',$type);
        $this->assign('status',$status);
        $this->assign('lei',$lei);
        $this->assign('show',$page);
        // 渲染模板输出

        return $this->fetch();
    }

    //订单导出
    public function orderzongxsexcel_out()
    {
        $piostdata = $this->request->post('arr/a',0);
        //$path = '/filexlsx/datashoporder.xlsx';
        $path = '/filexlsx/'.md5(time().rand(100000,999999)).'.xlsx';
        $name = '总订单列表';
        $title = [
            '订单号',
            '用户ID',
            '支付方式',
            '状态',
            '类型',
            '金额',
            '实际金额',
            '支付时间',
        ];
        $url = 'http://'.$_SERVER['HTTP_HOST'].$path;
        $d = [];
        //查询订单
        $where['order_id'] = ['in',implode(',',$piostdata)];
        $order_data = Db::name('order')->where($where)->select();

        $zhifutype = [
            '1' => '支付宝',
            '2' => '微信',
            '3' => '银行卡',
            '4' => '通证',
            '5' => '扑满',
            '6' => '其他',
            '7' => '其他',
            '8' => '其他',
            '9' => '其他',
        ];

        $zfzhaungtai = [
            '0' => '未支付',
            '1' => '已支付'
        ];

        $zfleixing = [
            '1' => '实名认证',
            '2' => '开通会员',
            '3' => '续费会员',
            '4' => '购买商品',
            '5' => '通证申购',
            '6' => '公益',
            '7' => '其他',
            '8' => '其他',
            '9' => '其他',
        ];

        foreach ($order_data as $k => $v)
        {
            $d[$k]['订单号'] = $v['order_sn'];
            $d[$k]['用户ID'] = $v['user_id'];
            $d[$k]['支付方式'] = $v['payment_type']?$zhifutype[$v['payment_type']]:'暂无';
            $d[$k]['状态'] = $v['order_status']?$zfzhaungtai[$v['order_status']]:'未支付';
            $d[$k]['类型'] = $v['order_type']?$zfleixing[$v['order_type']]:'暂无';
            $d[$k]['金额'] = $v['need_money'];
            $d[$k]['实际金额'] = $v['money'];
            $d[$k]['支付时间'] = $v['pay_time']?date(' Y-m-d H:i:s',$v['pay_time']):'暂无';
        }

        $data = $d;
        $odata = wps($name,$title,$data,ROOT_PATH.'/public'.$path);

        if($odata){
            //return jsonSuccess(200,"<a href='". $url ."'>点击立即下载</a>  ".$url,['url' =>$url ]);
            return jsonSuccess(200,"<a href='". $url ."'>点击此处文字立即下载后在右上角下载图标查看</a>  ");
        }else{
            return jsonError(500,'当前人数太多，处理失败，请稍后再试','');
        }
    }

}
