<?php
namespace app\admin\controller;

use app\common\model\VyangAdminPush;
use think\Db;
use think\Request;

/**
 * 价格
 * Class Price
 * @package app\admin\controller
 */
class Price extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','7');
    }

    /**
     * 主页
     */
    public function index()
    {
        $page = '';
        $map = [];
        $list = PageSeach2('ds_price', $map,[], 'day asc', 10, false, Request::instance()->param());
        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
        }

        // 渲染模板输出
        $this->assign('show',$page);
        $this->assign('list',$list);
        return $this->fetch();
    }
    public function price_add()
    {
        $day = date('Y-m-d');
        $this->assign('day',$day);
        return $this->fetch();
    }
    //处理添加
    public function price_add_edit()
    {
        $day    = $this->request->post('day');
        $price    = $this->request->post('price');
        if(empty($price))
        {
            ajaxError('请填写价格');
        }
        if(!is_numeric($price))
        {
            ajaxError('请填写有效价格');
        }
        if(!isDatetime($day))
        {
            ajaxError('请填写正确的日期！');
        }
        $data = [
            'day'   => $day,
            'val'   => $price,
        ];
        $res = Db::name('price')->insert($data);
        caozuo($res);
    }
    public function price_zd_edit()
    {
        $id     = $this->request->post('id');
        $type   = $this->request->post('type');
        $name   = $this->request->post('name');
        $val    = $this->request->post('val');
        if(!empty($id) && !empty($type))
        {
            if($type == 'edit')
            {
                //编辑修改
                if(!empty($name))
                {
                    $data = [
                        $name => $val
                    ];
                    $res = Db::name('price')->where('price_id',$id)->update($data);
                }else{
                    jsonError('10001','缺少修改内容');
                }
            }else{
                //删除
                $res = Db::name('price')->where('price_id',$id)->delete();
            }
            //返回结果
            caozuo($res);
        }
    }
}
