<?php
namespace app\admin\controller;

use app\admin\controller\Common;

use app\common\model\VyangAdminPush;
use OSS\Core\OssException;
use think\Db;
use think\Request;
use think\Loader;


/**
 *  IM管理
 * Class Puman
 * @package app\admin\controller
 */
class Redwrap extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','20');
    }

    //通证回收列表
    public function redwrap_list(){

        // 查询数据 并且每页显示10条数据
        $cont    = $this->request->get('cont');
        $type       = $this->request->get('type');
        $status     = $this->request->get('status');
        $lei     = $this->request->get('lei');

        $map    = [];
        $page = '';

        if(!empty($cont))
        {
            $cont_type    = $this->request->get('cont_type');
            if($cont_type == 1)
            {
                $map['redwrap_out_id']       = ['eq', $cont];
            }
            if($cont_type == 2)
            {
                $map['user_id']       = ['eq', $cont];
            }
            if($cont_type == 3)
            {
                $map['redwrap_user_id']       = ['eq', $cont];
            }
        }
        if(!empty($type)){
            $map['status'] = ['eq', $type];//'状态： 0未领取，1领取中/展示中 ，2已领完  ，3已过期 4申述中 5后台处理成功 6后台处理退回'
        }
        if(!empty($status))
        {
            $map['class']       = ['eq', $status];//'红包类型 id 1通证红包 2扑满红包'
        }

        $list   = PageSeach('redwrap_out', $map,[], 'redwrap_out_id desc', '10', false, Request::instance()->param());

        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
            foreach ($list as $k => $v)
            {
                if(!empty($v['time']))
                {
                    $list[$k]['time']        = replaceTime($v['time']);
                }else{
                    $list[$k]['time']        = '';
                }
                if(!empty($v['time_over']))
                {
                    $list[$k]['time_over']        = replaceTime($v['time_over']);
                }else{
                    $list[$k]['time_over']        = '';
                }
            }
        }

        if(!empty($list))
        {
            $list = _xss($list);
        }

        // 把分页数据赋值给模板变量list
        $this->assign('order',$list);
        $this->assign('show',$page);
        // 渲染模板输出

        return $this->fetch();
    }

    public function redwrap_edit(){
        $id = $this->request->post('id');
        $type = $this->request->post('type');
        $cont = $this->request->post('cont');

        if(empty($cont)){
            ajaxError('请填写原因');
        }
        $res_r = Db::name('redwrap_out')->where('redwrap_out_id',$id)->find();
        if(empty($res_r)){
            ajaxError('没有该记录');
        }
        if(!in_array($res_r['status'],[1,4])){
            ajaxError('只有展示中和申述中才可操作');
        }

        if ($type == 1) {//下发
            $zt = 5;
            $up_fa = Db::name('redwrap_out')->where('redwrap_out_id',$id)->update(['status' => $zt,'cont'=>$cont]);
            if(empty($up_fa)){
                ajaxError('修改状态失败，请稍后再试');
            }
            switch ($res_r['class']){
                case '1':
                    $info =[
                        'user_id'   => $res_r['redwrap_user_id'],
                        'num'       => $res_r['money'],
                        'desc'      => '红包-收到用户['.$res_r['user_id'].']',
                        'type'      => 3,//3通证 4扑满
                        'key'       => config('key'),    //key
                    ];
                    $url = 'http://127.0.0.1:9510/system/add_gold_integral_dian';
                    VyangAdminPush::https_post($url, $info);
                    $insert = [
                        'user_id' => $res_r['redwrap_user_id'],
                        'redwrap_out_id' => $res_r['redwrap_out_id'],
                        'user_id_out' => $res_r['user_id'],
                        'money' => $res_r['money'],
                        'class' => $res_r['class'],
                        'style' => $res_r['style'],
                        'time' => time(),
                    ];
                    Db::name('redwrap_get')->insertGetId($insert);
                    ajaxSuccess('操作成功');
                    break;
                case '2':
                    $info =[
                        'user_id'   => $res_r['redwrap_user_id'],
                        'num'       => $res_r['money'],
                        'desc'      => '红包-收到用户['.$res_r['user_id'].']',
                        'type'      => 4,//3通证 4扑满
                        'key'       => config('key'),    //key
                    ];
                    $url = 'http://127.0.0.1:9510/system/add_gold_integral_dian';
                    $insert = [
                        'user_id' => $res_r['redwrap_user_id'],
                        'redwrap_out_id' => $res_r['redwrap_out_id'],
                        'user_id_out' => $res_r['user_id'],
                        'money' => $res_r['money'],
                        'class' => $res_r['class'],
                        'style' => $res_r['style'],
                        'time' => time(),
                    ];
                    Db::name('redwrap_get')->insertGetId($insert);
                    VyangAdminPush::https_post($url, $info);
                    ajaxSuccess('操作成功');
                    break;
                default:
                    ajaxError('没有该类别');
                    break;
            }
        }else{
            $zt = 6;
            $up_fa = Db::name('redwrap_out')->where('redwrap_out_id',$id)->update(['status' => $zt,'cont'=>$cont]);
            if(empty($up_fa)){
                ajaxError('修改状态失败，请稍后再试');
            }
            switch ($res_r['class']){
                case '1':
                    $info =[
                        'user_id'   => $res_r['user_id'],
                        'num'       => $res_r['money'],
                        'desc'      => '红包退回-发送给['.$res_r['redwrap_user_id'].']',
                        'type'      => 3,//3通证 4扑满
                        'key'       => config('key'),    //key
                    ];
                    $url = 'http://127.0.0.1:9510/system/add_gold_integral_dian';
                    VyangAdminPush::https_post($url, $info);
                    ajaxSuccess('操作成功');
                    break;
                case '2':
                    $info =[
                        'user_id'   => $res_r['user_id'],
                        'num'       => $res_r['money'],
                        'desc'      => '红包退回-发送给['.$res_r['redwrap_user_id'].']',
                        'type'      => 4,//3通证 4扑满
                        'key'       => config('key'),    //key
                    ];
                    $url = 'http://127.0.0.1:9510/system/add_gold_integral_dian';
                    VyangAdminPush::https_post($url, $info);
                    ajaxSuccess('操作成功');
                    break;
                default:
                    ajaxError('没有该类别');
                    break;
            }
        }
    }

}

