<?php
namespace app\admin\controller;

use think\Db;

/**
 * 获取
 * Class Set
 * @package app\admin\controller
 */
class Set extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','2');
    }

    /**
     * 获取页面
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function index()
    {
        //加载是否选中
        $this->assign('active','2');
        $data = [];
        $this->xiao_redis->select(0);

        $data[] = [
            'name'  => '加密key',
            'key'   => 'set_key',
            'value' => $this->xiao_redis->get('set_key'),
        ];
        $data[] = [
            'name'  => '网站url地址',
            'key'   => 'web_url',
            'value' => $this->xiao_redis->get('web_url'),
        ];
        $data[] = [
            'name'  => '接口url地址',
            'key'   => 'url',
            'value' => $this->xiao_redis->get('url'),
        ];
        $data[] = [
            'name'  => '注册url地址',
            'key'   => 'reg_url',
            'value' => $this->xiao_redis->get('reg_url'),
        ];
        $data[] = [
            'name'  => '交易url地址',
            'key'   => 'get_jishi_url',
            'value' => $this->xiao_redis->get('get_jishi_url'),
        ];
        $data[] = [
            'name'  => '扑满储备url地址',
            'key'   => 'get_puman_url',
            'value' => $this->xiao_redis->get('get_puman_url'),
        ];
        $data[] = [
            'name'  => '超级密码(不开起则设置空)',
            'key'   => 'super_password',
            'value' => $this->xiao_redis->get('super_password'),
        ];
        $data[] = [
            'name'  => 'token过期时间(单位：天)',
            'key'   => 'set_token_out_time',
            'value' => $this->xiao_redis->get('set_token_out_time'),
        ];
        $data[] = [
            'name'  => '是否开启接口加密(1是 0不是)',
            'key'   => 'is_signature',
            'value' => $this->xiao_redis->get('is_signature'),
        ];
        $data[] = [
            'name'  => '异步服务器redis库(指定 8 9 11)',
            'key'   => 'async_db',
            'value' => $this->xiao_redis->get('async_db'),
        ];
        $data[] = [
            'name'  => '是否开启发送短信(1是 0不是)',
            'key'   => 'is_code',
            'value' => $this->xiao_redis->get('is_code'),
        ];
        $data[] = [
            'name'  => '是否开启账号密码登录 1能 0不能',
            'key'   => 'login_password',
            'value' => $this->xiao_redis->get('login_password'),
        ];
        $data[] = [
            'name'  => '是否开启注册(1是 0不是)',
            'key'   => 'is_register',
            'value' => $this->xiao_redis->get('is_register'),
        ];
        $data[] = [
            'name'  => '是否能实名 1能 0不能',
            'key'   => 'is_user_auth',
            'value' => $this->xiao_redis->get('is_user_auth'),
        ];
        $data[] = [
            'name'  => '是否开启支付 1能 0不能',
            'key'   => 'is_pay',
            'value' => $this->xiao_redis->get('is_pay'),
        ];
        $data[] = [
            'name'  => '是否开启兑换任务包 (1开启 0关闭)',
            'key'   => 'rent_status',
            'value' => $this->xiao_redis->get('rent_status'),
        ];
        $data[] = [
            'name'  => '是否开启释放任务包 (1开启 0关闭)',
            'key'   => 'receive_reward_status',
            'value' => $this->xiao_redis->get('receive_reward_status'),
        ];
        $data[] = [
            'name'  => '任务广告次数',
            'key'   => 'task_day',
            'value' => $this->xiao_redis->get('task_day'),
        ];
        $data[] = [
            'name'  => '几天不做任务掉活跃度和贡献值(单位：天)',
            'key'   => 'day_diao_hyd_gxz',
            'value' => $this->xiao_redis->get('day_diao_hyd_gxz'),
        ];
        $data[] = [
            'name'  => '是否开公益支付 (1开启 0关闭)',
            'key'   => 'get_gy_buy_status',
            'value' => $this->xiao_redis->get('get_gy_buy_status'),
        ];
        
        $data[] = [
            'name'  => '三方电影回调',
            'key'   => 'callback_dianying_url',
            'value' => $this->xiao_redis->get('callback_dianying_url'),
        ];
        $data[] = [
            'name'  => ' 亿奇达回调',
            'key'   => 'callback_yiqida_url',
            'value' => $this->xiao_redis->get('callback_yiqida_url'),
        ];
        $data[] = [
            'name'  => ' 是否开启线下店铺入驻1开启 0不开启',
            'key'   => 'is_offline_status',
            'value' => $this->xiao_redis->get('is_offline_status'),
        ];
        $data[] = [
            'name'  => ' 线下入驻费用',
            'key'   => 'offline_money',
            'value' => $this->xiao_redis->get('offline_money'),
        ];
        $data[] = [
            'name'  => '是否开启影票兑换通证(1开启 0关闭)',
            'key'   => 'yp_to_tz',
            'value' => $this->xiao_redis->get('yp_to_tz'),
        ];
        $data[] = [
            'name'  => '是否开启通证兑换影票(1开启 0关闭)',
            'key'   => 'tz_to_yp',
            'value' => $this->xiao_redis->get('tz_to_yp'),
        ];
        $data[] = [
            'name'  => '是否开启通证数据-申购(1开启 0关闭)',
            'key'   => 'tz_sg_buy',
            'value' => $this->xiao_redis->get('tz_sg_buy'),
        ];
        $data[] = [
            'name'  => '是否开启通证数据-回收(1开启 0关闭)',
            'key'   => 'tz_hs_do_status',
            'value' => $this->xiao_redis->get('tz_hs_do_status'),
        ];
        $data[] = [
            'name'  => '是否开启扑满储备兑换(1开启 0关闭)',
            'key'   => 'puman_cb_dh',
            'value' => $this->xiao_redis->get('puman_cb_dh'),
        ];
        $data[] = [
            'name'  => '是否开启扑满-赎回(1开启 0关闭)',
            'key'   => 'puman_sh_do',
            'value' => $this->xiao_redis->get('puman_sh_do'),
        ];

        $data[] = [
            'name'  => '是否开启交易-通证-上架(1开启 0关闭)',
            'key'   => 'tz_grounding_status',
            'value' => $this->xiao_redis->get('tz_grounding_status'),
        ];
        $data[] = [
            'name'  => '是否开启交易-通证-置换(1开启 0关闭)',
            'key'   => 'tz_displace_status',
            'value' => $this->xiao_redis->get('tz_displace_status'),
        ];
        $data[] = [
            'name'  => '是否开启交易-扑满-上架(1开启 0关闭)',
            'key'   => 'pm_grounding_status',
            'value' => $this->xiao_redis->get('pm_grounding_status'),
        ];
        $data[] = [
            'name'  => '是否开启交易-扑满-置换(1开启 0关闭)',
            'key'   => 'pm_displace_status',
            'value' => $this->xiao_redis->get('pm_displace_status'),
        ];
        $data[] = [
            'name'  => '是否开启发红包(1开启 0关闭)',
            'key'   => 'redwrap_switch',
            'value' => $this->xiao_redis->get('redwrap_switch'),
        ];
        $data[] = [
            'name'  => '1通证=多少人民币(单位：元)',
            'key'   => 'tz_to_rmb',
            'value' => $this->xiao_redis->get('tz_to_rmb'),
        ];
        $data[] = [
            'name'  => '扑满赎回固定一笔手续费(单位：USDT)',
            'key'   => 'puman_sh_shouxufei',
            'value' => $this->xiao_redis->get('puman_sh_shouxufei'),
        ];
        $data[] = [
            'name'  => '是否开启仲裁(1开启 0关闭)',
            'key'   => 'hongbao_zhongcai',
            'value' => $this->xiao_redis->get('hongbao_zhongcai'),
        ];
        $data[] = [
            'name'  => '首页(院线URL)',
            'key'   => 'sy_nav_yx_url',
            'value' => $this->xiao_redis->get('sy_nav_yx_url'),
        ];
        $data[] = [
            'name'  => 'IM_星级群ID',
            'key'   => 'im_xingji_number',
            'value' => $this->xiao_redis->get('im_xingji_number'),
        ];
        $data[] = [
            'name'  => 'IM_VIP群ID',
            'key'   => 'im_vip_number',
            'value' => $this->xiao_redis->get('im_vip_number'),
        ];
        $data[] = [
            'name'  => '允许账号密码登录的手机【,英文逗号隔开】',
            'key'   => 'is_login_u_users',
            'value' => $this->xiao_redis->get('is_login_u_users'),
        ];
        $data[] = [
            'name'  => '话费充值开关(1开 0关)',
            'key'   => 'is_huafei_buy',
            'value' => $this->xiao_redis->get('is_huafei_buy'),
        ];
        $data[] = [
            'name'  => '买电影票开关(1开 0关)',
            'key'   => 'is_dianying_buy',
            'value' => $this->xiao_redis->get('is_dianying_buy'),
        ];
        $data[] = [
            'name'  => '加入帮帮开关(1开 0关)',
            'key'   => 'bang_is_on',
            'value' => $this->xiao_redis->get('bang_is_on'),
        ];
        $data[] = [
            'name'  => '加入帮帮通证金额',
            'key'   => 'bang_money',
            'value' => $this->xiao_redis->get('bang_money'),
        ];
        $data[] = [
            'name'  => '第三方VIP福利放映厅',
            'key'   => 'dsf_vip_fang',
            'value' => $this->xiao_redis->get('dsf_vip_fang'),
        ];
        $this->assign('set',$data);
        $data[] = [
            'name'  => '[勿动]计划任务更新pq个数',
            'key'   => 'pq_num_update',
            'value' => $this->xiao_redis->get('pq_num_update'),
        ];
        $this->assign('set',$data);
        // 渲染模板输出


//        $this->xiao_redis->set('file_extension',json_encode([
//            'jpg','jpeg','png','gif','bmp','tif','pcx','tga','exif','fpx','svg','psd','cdr','pcd','dxf','ufo','ai','raw','WMF','webp','avif','apng','pdf','xlsx','rtf','mp4','mp3','rm','rmvb','mkv','3gp','mov','xls','xlsx',
//        ]));
//
//        $this->xiao_redis->set('get_shop_logos',json_encode([
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_1.jpg',
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_2.jpg',
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_3.jpg',
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_4.jpg',
//        ]));
//
//        $this->xiao_redis->set('shouma',json_encode([
//            660001,
//            660002,
//        ]));
        return $this->fetch();

    }
    //设置支付通知邮箱
    public function set_youxiang()
    {
        $set_youxiang        =$this->xiao_redis->get('set_youxiang');
        if(!empty($set_youxiang))
        {
            $set_youxiang = implode(PHP_EOL,json_decode($set_youxiang,true));
        }else{
            $set_youxiang = '';
        }
        $this->assign('data',$set_youxiang);
        $this->assign('name','set_youxiang');
        return $this->fetch();
    }
    /**
     * 添加
     */
    public function add()
    {
        return $this->fetch();
    }

    /**
     * 处理添加
     */
    public function edit_add()
    {
        $key = $this->request->param('key');
        $val = $this->request->param('val','');
        $arr = $this->request->param('arr/a');
        if(empty($key))
        {
            ajaxError('请填写key');
        }
        $val = strval($val);
//        if(empty($val))
//        {
//            if(empty($arr))
//            {
//                ajaxError('请填写内容');
//            }else{
//                $val = json_encode($val);
//            }
//        }else{
//            $val = strval($val);
//        }
        //设置一下
        $this->xiao_redis->select(0);
        $res = $this->xiao_redis->set($key,$val);
        if($res)
        {
            ajaxSuccess('操作成功');
        }else{
            ajaxError('操作失败');
        }
    }
    /**
     * 判断是否是json
     * @param $string
     * @return bool
     */
    protected function is_not_json($string)
    {
        @json_decode($string);
        return (json_last_error() === JSON_ERROR_NONE);
    }
    /**
     * 1用户协议 2隐私协议 3七牛云 4支付 5签到规则 6app版本 7提现说明
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function xieyi()
    {
        $type = $this->request->param('type','1');
        $this->assign('type',$type);
        switch ($type)
        {
            case '1':
                #用户协议
                $system = \app\common\model\Common::get_system();
                $this->assign('cont',$system['xieyi_user']);
                return $this->fetch('cont');
                break;
            case '2':
                #隐私协议
                $system = \app\common\model\Common::get_system();
                $this->assign('cont',$system['xieyi_privacy']);
                return $this->fetch('cont');
                break;
            case '3':
                #七牛云配置
                $data['qnybk']  = $this->xiao_redis->get('qnybk');
                $data['qnyak']  = $this->xiao_redis->get('qnyak');
                $data['qnysk']  = $this->xiao_redis->get('qnysk');
                $data['qnyurl'] = $this->xiao_redis->get('qnyurl');
                $this->assign('data',$data);
                return $this->fetch('cont3');
                break;
            case '4':
                #支付宝配置
                $data['ali_app_id']         = $this->xiao_redis->get('ali_app_id');
                $data['ali_private_key']    = $this->xiao_redis->get('ali_private_key');
                $data['ali_notify_url']     = $this->xiao_redis->get('ali_notify_url');
                $data['ali_public_key']     = $this->xiao_redis->get('ali_public_key');
                $this->assign('data',$data);
                return $this->fetch('cont4');
                break;
            case '5':
                #微信配置
                $data['wx_app_id']          = $this->xiao_redis->get('wx_app_id');
                $data['wx_mch_id']          = $this->xiao_redis->get('wx_mch_id');
                $data['wx_notify_url']      = $this->xiao_redis->get('wx_notify_url');
                $data['wx_key']             = $this->xiao_redis->get('wx_key');
                $data['wx_app_secret']      = $this->xiao_redis->get('wx_app_secret');
                $this->assign('data',$data);
                return $this->fetch('cont14');
                break;
            case '6':
                #app版本
                $app_version     = $this->xiao_redis->get('app_version');
                $app_version     = json_decode($app_version,true);
                $data['ios']     = $app_version['ios'];
                $data['android'] = $app_version['android'];
                $this->assign('data',$data);
                return $this->fetch('cont6');
                break;
            case '7':
                #提现说明
                $system = \app\common\model\Common::get_system();
                $this->assign('cont',$system['tixian']);
                return $this->fetch('cont');
                break;
            case '8':
                //关于我们
                $system = \app\common\model\Common::get_system();
                $this->assign('cont',$system['about_us']);
                return $this->fetch('cont');
                break;
            case '9':
                //交易规则
                $system = Db::name('admin_set')->where('set_cname','jiaoyi_guize')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');

            case '10':
                //影票说明
                $system = Db::name('admin_set')->where('set_cname','yingpiao_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '11':
                //通证说明
                $system = Db::name('admin_set')->where('set_cname','tongzheng_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '12':
                //扑满说明
                $system = Db::name('admin_set')->where('set_cname','puman_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '13':
                //贡献值说明
                $system = Db::name('admin_set')->where('set_cname','gongxianzhi_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '14':
                //活跃度说明
                $system = Db::name('admin_set')->where('set_cname','huoyuedu_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '15':
                //星级分红说明
                $system = Db::name('admin_set')->where('set_cname','xj_fenhong_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '16':
                //证票闪兑
                $system = Db::name('admin_set')->where('set_cname','zpsd_sm')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '17':
                //铺满排行榜
                $system = Db::name('admin_set')->where('set_cname','phb_puman')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            case '18':
                //影票排行榜
                $system = Db::name('admin_set')->where('set_cname','phb_yingpiao')->value('set_cvalue');
                $this->assign('cont',$system);
                return $this->fetch('cont');
            default:
                jsonError('10001','类型选择错误');
                break;
        }
    }
    /**
     * 编辑所有
     */
    public function edit_all()
    {
        $type = $this->request->post('type','1');
        switch ($type)
        {
            case '1':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'xieyi_user'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont ]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '2':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'xieyi_privacy'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont ]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '3':
                $qnybk = $this->request->post('qnybk');
                $qnyak = $this->request->post('qnyak');
                $qnysk = $this->request->post('qnysk');
                $qnyurl = $this->request->post('qnyurl');
                if(!empty($qnybk) && !empty($qnyak) && !empty($qnysk) && !empty($qnyurl))
                {
                    //设置一下
                    $this->xiao_redis->select(0);
                    $this->xiao_redis->set('qnybk',$qnybk);
                    $this->xiao_redis->set('qnyak',$qnyak);
                    $this->xiao_redis->set('qnysk',$qnysk);
                    $res = $this->xiao_redis->set('qnyurl',$qnyurl);
                    if($res)
                    {
                        ajaxSuccess('操作成功');
                    }else{
                        ajaxError('操作失败');
                    }
                }else{
                    ajaxError('请填写完整内容');
                }
                break;
            case '4':
                $ali_app_id = $this->request->post('ali_app_id');
                $ali_private_key = $this->request->post('ali_private_key');
                $ali_public_key = $this->request->post('ali_public_key');
                $ali_notify_url = $this->request->post('ali_notify_url');
                if(!empty($ali_app_id) && !empty($ali_private_key) && !empty($ali_public_key) && !empty($ali_notify_url))
                {
                    //设置一下
                    $this->xiao_redis->select(0);
                    $this->xiao_redis->set('ali_app_id',$ali_app_id);
                    $this->xiao_redis->set('ali_private_key',$ali_private_key);
                    $this->xiao_redis->set('ali_public_key',$ali_public_key);
                    $res = $this->xiao_redis->set('ali_notify_url',$ali_notify_url);
                    if($res)
                    {
                        ajaxSuccess('操作成功');
                    }else{
                        ajaxError('操作失败');
                    }
                }else{
                    ajaxError('请填写完整内容');
                }
                break;
            case '5':
                $wx_app_id = $this->request->post('wx_app_id');
                $wx_mch_id = $this->request->post('wx_mch_id');
                $wx_app_secret = $this->request->post('wx_app_secret');
                $wx_notify_url = $this->request->post('wx_notify_url');
                $wx_key = $this->request->post('wx_key');
                if(!empty($wx_app_id) && !empty($wx_mch_id) && !empty($wx_app_secret) && !empty($wx_notify_url) && !empty($wx_key))
                {
                    //设置一下
                    $this->xiao_redis->select(0);
                    $this->xiao_redis->set('wx_app_id',$wx_app_id);
                    $this->xiao_redis->set('wx_mch_id',$wx_mch_id);
                    $this->xiao_redis->set('wx_app_secret',$wx_app_secret);
                    $this->xiao_redis->set('wx_key',$wx_key);
                    $res = $this->xiao_redis->set('wx_notify_url',$wx_notify_url);
                    if($res)
                    {
                        ajaxSuccess('操作成功');
                    }else{
                        ajaxError('操作失败');
                    }
                }else{
                    ajaxError('请填写完整内容');
                }
                break;
            case '6':
                $data['ios']['version_name']        = $this->request->post('ios_version_name');
                $data['ios']['version_code']        = $this->request->post('ios_version_code');
                $data['ios']['version_url']         = $this->request->post('ios_version_url');
                $data['ios']['version_desc']        = $this->request->post('ios_version_desc');
                $data['ios']['version_upgrade']     = $this->request->post('ios_version_upgrade');

                $data['android']['version_name']    = $this->request->post('android_version_name');
                $data['android']['version_code']    = $this->request->post('android_version_code');
                $data['android']['version_url']     = $this->request->post('android_version_url');
                $data['android']['version_desc']        = $this->request->post('android_version_desc');
                $data['android']['version_upgrade']     = $this->request->post('android_version_upgrade');
                //设置一下
                $this->xiao_redis->select(0);
                $res = $this->xiao_redis->set('app_version',json_encode($data));
                if($res)
                {
                    ajaxSuccess('操作成功');
                }else{
                    ajaxError('操作失败');
                }
                break;
            case '7':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'tixian'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont ]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '8':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'about_us'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont ]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '9':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'jiaoyi_guize'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont ]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;

            case '10':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'yingpiao_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '11':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'tongzheng_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '12':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'puman_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '13':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'gongxianzhi_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '14':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'huoyuedu_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '15':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'xj_fenhong_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '16':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'zpsd_sm'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '17':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'phb_puman'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            case '18':
                $cont = $this->request->post('cont');
                if(empty($cont))
                {
                    ajaxError('内容不能为空');
                }
                $where = [
                    'set_cname' => 'phb_yingpiao'
                ];
                $res = Db::name('admin_set')->where($where)->update(['set_cvalue' =>$cont]);
                if($res)
                {
                    jsonSuccess('200','操作成功');
                }else{
                    jsonError('10001','操作失败 请重试');
                }
                break;
            default:
                jsonError('10001','类型选择错误');
                break;
        }
    }
    public function asdasdasda()
    {
        for ($i=6010;$i<6133;$i++)
        {
            $info = Db::name('cash')->where('cash_id',$i)->field('user_id,cash_money_2')->find();
//            $this->xiao_redis->select(5);
//            $this->xiao_redis->incrBy($info['user_id'].'_arrears',(int)$info['cash_money_2']);
            $info['cash_money_2'] = (int)$info['cash_money_2'];
            pr($info);
        }
    }

    /**
     * 添加系统通知
     */
    public function get_notice_add()
    {
        $cont = $this->request->post('cont');
        if(empty($cont))
        {
            return $this->fetch();
        }else{
            //处理添加
            $get_notice = $this->xiao_redis->get('get_notice');
            $get_notice = json_decode($get_notice,true);
            $get_notice[] = $cont;
            $get_notice = array_merge($get_notice);
            //设置一下
            $this->xiao_redis->set('get_notice',json_encode($get_notice));
            ajaxSuccess('操作成功');
        }
    }
    /**
     * 添加新手帮助
     */
    public function get_help_add()
    {
        $title = $this->request->post('title');
        $cont = $this->request->post('cont');
        if(!empty($cont) && !empty($title))
        {
            //处理添加
            $get_help = $this->xiao_redis->get('get_help');
            $get_help = json_decode($get_help,true);
            $data['name'] = $title;
            $data['cont'] = $cont;
            $get_help[] = $data;
            $get_help = array_merge($get_help);
            //设置一下
            $this->xiao_redis->set('get_help',json_encode($get_help));
            ajaxSuccess('操作成功');
        }else{
            return $this->fetch();
        }
    }
    public function set_robot_cont()
    {
        $robot_cont = $this->request->post('robot_cont','');
        if(empty($robot_cont))
        {
            $info = \app\common\model\Common::get_system();
            $robot_cont = $info['robot_cont'];
            $this->assign('robot_cont',$robot_cont);
            return $this->fetch();
        }else{
            //修改
            $res = Db::name('admin_set')->where('set_cname','robot_cont')->update(['set_cvalue' =>$robot_cont ]);
            if($res)
            caozuo($res);
        }
    }
    public function set_robot_ci()
    {
        $room_pipei_chi        =$this->xiao_redis->get('room_pipei_chi');
        if(!empty($room_pipei_chi))
        {
            $room_pipei_chi = implode(PHP_EOL,json_decode($room_pipei_chi,true));
        }else{
            $room_pipei_chi = '';
        }
        $this->assign('data',$room_pipei_chi);
        $this->assign('name','room_pipei_chi');
        return $this->fetch();
    }
}
