<?php
namespace app\admin\controller;

use app\admin\controller\Common;

use app\common\model\VyangAdminPush;
use OSS\Core\OssException;
use think\Db;
use think\Request;
use think\Loader;


/**
 *  通证管理
 * Class Puman
 * @package app\admin\controller
 */
class Tongzheng extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','19');
    }

    //通证回收列表
    public function tz_huishou_list(){

        // 查询数据 并且每页显示10条数据
        $cont    = $this->request->get('cont');
        $type       = $this->request->get('type');
        $status     = $this->request->get('status');
        $lei     = $this->request->get('lei');

        $map    = [];
        $page = '';

        $begintime     = $this->request->get('begintime',0);
        //申请时间 $begintime 2020-04-22 时间字符串
        if(!empty($begintime)){
            $time = strtotime($begintime);//开始时间
            $end_time = strtotime(date('Y-m-d 23:59:59',strtotime($begintime)));//结束时间
            $map['time']      = ['between', [$time,$end_time]];
        }

        if(!empty($cont))
        {
            $cont_type    = $this->request->get('cont_type');
            if($cont_type == 1)
            {
                $map['hs_id']       = ['eq', $cont];
            }
            if($cont_type == 2)
            {
                $map['user_id']       = ['eq', $cont];
            }
            if($cont_type == 3)
            {
                $map['ali_account']       = ['eq', $cont];
            }
        }

        $list   = PageSeach('tz_hs', $map,[], 'hs_id desc', '1000', false, Request::instance()->param());

        if(!empty($list))
        {
            $page = $list->render();
            $list = $list->all();
            foreach ($list as $k => $v)
            {
                if(!empty($v['time']))
                {
                    $list[$k]['time']        = replaceTime($v['time']);
                }else{
                    $list[$k]['time']        = '';
                }
            }
        }

        if(!empty($list))
        {
            $list = _xss($list);
        }

        // 把分页数据赋值给模板变量list
        $this->assign('order',$list);
        $this->assign('show',$page);
        // 渲染模板输出

        return $this->fetch();
    }

    //通过拒绝
    public function tz_huishou_sub(){
        $id = $this->request->post('id');
        $type = $this->request->post('type');
        $cont = $this->request->post('cont');
        $rrr = Db::name('tz_hs')->where('hs_id', $id)->find();
        if(!$rrr)
        {
            ajaxError('找不到该订单！');
        }
        if($rrr['type'] != 0)
        {
            ajaxError('该订单已处理！');
        }
        if ($type == 1) {
            //支付宝提现
            $info =[
                'id'    => $id,
                'admin_id'    => $this->userInfo['id'],
                'key'   => config('key')
            ];
            $url = 'http://127.0.0.1:9510/system/ali_tixian';
            VyangAdminPush::https_post($url, $info);
            ajaxSuccess('操作成功');
        } else {
            if(empty($cont)){
                ajaxError('拒绝请填写原因');
            }
            $update = ['type' => 2,'cont' =>$cont];
            $res = Db::name('tz_hs')->where('hs_id', $id)->update($update);
            if ($res) {
                $info =[
                    'id'    => $id,
                    'type'  => 1,   //1通证回收退回 2扑满赎回退回
                    'key'   => config('key')
                ];
                $url = 'http://127.0.0.1:9510/system/tuihui_all';
                VyangAdminPush::https_post($url, $info);
                ajaxSuccess('操作成功');
            } else {
                ajaxError('操作失败,请重试');
            }
        }

    }

    /**导出
     * @return null
     * @throws \PHPExcel_Exception
     * @throws \PHPExcel_Reader_Exception
     * @throws \PHPExcel_Writer_Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function out_tz_hs_list(){
        $piostdata = $this->request->post('arr/a',0);
        $path = '/filexlsx/'.md5(time().rand(100000,999999)).'.xlsx';
        $name = '列表';
        $title = [
            '序号',
            '用户ID',
            '支付宝名',
            '支付宝号',
            '份额数量',
            '时间',
        ];
        $url = 'http://'.$_SERVER['HTTP_HOST'].$path;
        $d = [];
        //查询
        $where['hs_id'] = ['in',implode(',',$piostdata)];
        $order_data = Db::name('tz_hs')->where($where)->select();

        foreach ($order_data as $k => $v)
        {
            $d[$k]['序号'] = $v['hs_id'];
            $d[$k]['用户ID'] = $v['user_id'];
            $d[$k]['支付宝名'] = $v['ali_name']?$v['ali_name']:'暂无';
            $d[$k]['支付宝号'] = $v['ali_account']?$v['ali_account']:'无';
            $d[$k]['份额数量'] = $v['tongzheng'];
            $d[$k]['时间'] = replaceTime($v['time']);
        }

        $data = $d;
        $odata = wps($name,$title,$data,ROOT_PATH.'/public'.$path);

        if($odata){
            //return jsonSuccess(200,"<a href='". $url ."'>点击立即下载</a>  ".$url,['url' =>$url ]);
            return jsonSuccess(200,"<a href='". $url ."'>点击立即下载</a>  ");
        }else{
            return jsonError(500,'当前人数太多，处理失败，请稍后再试','');
        }
    }

}

