<?php
namespace app\admin\controller;

use app\admin\controller\Common;
use app\common\model\BtnumLog;
use app\common\model\UserContribution;
use app\common\model\VyangAdminPush;
use OSS\Core\OssException;
use think\Db;
use think\Request;
use think\Loader;


/**
 * 自营商城管理
 * Class Admindata
 * @package app\admin\controller
 */
class Zhuangxiu extends Common
{
    /**
     * 初始加载
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //加载是否选中
        $this->assign('active','11');
    }

    /**
     * 装修首页
     */
    public function zx_index()
    {

//        $urls = [
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_1.jpg',
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_2.jpg',
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_3.jpg',
//            'https://guotaooss.oss-cn-hangzhou.aliyuncs.com/banner/index_4.jpg',
//        ];
//        $this->xiao_redis->set('get_shop_logos',json_encode($urls));

        $this->xiao_redis->select(0);
        if($this->xiao_redis->get('get_index_logos')){
            $zx_value =  json_decode($this->xiao_redis->get('get_index_logos'),true);
        }else{
            $zx_value = [];
        }
        $this->assign('lunbotu',$zx_value);

        $this->xiao_redis->select(0);
        if($this->xiao_redis->get('get_index_banner_data')){
            $zx_value =  json_decode($this->xiao_redis->get('get_index_banner_data'),true);
        }else{
            $zx_value = [];
        }
        $this->assign('get_index_banner_data',$zx_value);

        return $this->fetch();
    }

    //轮播图提交
    public function zx_lbt_sub()
    {
        $zx_value                   =     $this->request->post('lunbotu/a','');

        $zx_value2 = $zx_value;

        $this->xiao_redis->select(0);
        //$redis_lunbotus = $this->xiao_redis->get('get_index_logos');print_r($redis_lunbotus);exit;
        $zx_value2 = json_encode($zx_value2,JSON_UNESCAPED_SLASHES);
        //替换缓存
        $this->xiao_redis->set('get_index_logos',$zx_value2);

        return jsonSuccess(200,'保存成功','');
    }

    //轮播图第二版提交
    public function zx_lbt_sub_data()
    {
        $zx_value2                   =     $this->request->post('lunbotu/a','');
        $url                   =     $this->request->post('url/a','');



        $this->xiao_redis->select(0);
        $new_array = [];
        foreach ($zx_value2 as $k => $v){
            $new_array[$k]['img'] = $v;
            $new_array[$k]['url'] = $url[$k];
        }

        $zx_value2 = json_encode($new_array,JSON_UNESCAPED_SLASHES);

        //替换缓存
        $this->xiao_redis->set('get_index_banner_data',$zx_value2);

        return jsonSuccess(200,'保存成功','');
    }



    //公告列表
    public function gonggaolist(){

        $order = 'notice_id desc';

        //查询下级列表
        $map     = [];

        $list = PageSeach('notice', $map,[], $order, '20', false, Request::instance()->param());
        if (!empty($list))
        {

            $listall = $list->all();//【重点】 将分页数据转成实际数据数组，否则不能修改
            $page = $list->render();
            foreach ($listall as $k => $v)
            {
                $listall[$k]['time'] = date('Y-m-d H:i:s',$v['time']);
            }

            $listall = _xss($listall);
        }else{
            $listall = [];
            $page = '';
        }

        // 把分页数据赋值给模板变量list
        $this->assign('user', $listall);
        $this->assign('show', $page);


        return $this->fetch();
    }

    //添加公告
    public function gonggao_insert(){


        return $this->fetch();
    }

    //添加公告提交
    public function gonggao_insert_sub(){
        $cont               =     $_POST['cont'];
        $img               =     $this->request->post('img','');
        $image               =     $this->request->post('image','');
        $title               =     $this->request->post('title','');

        if(empty($cont)){
            return jsonError(500,'内容不能为空','');
        }
        if(empty($title)){
            return jsonError(500,'标题不能为空','');
        }

        $insert = [
          //'cont'  => htmlspecialchars($cont),
          'cont'  => $cont,
          'img' => $img?$img:'',
          'time'  => time(),
          'title'  => $title,
        ];

        $res = Db::name('notice')->insert($insert);

        if($res)
        {
            return jsonSuccess(200,'保存成功','');
        }else{
            return jsonError(500,'保存失败','');
        }

    }

    //修改公告
    public function gonggao_edit(){
        $notice_id              =     $this->request->post('type',0);
        $cont               =     $this->request->post('cont','');
        $img               =     $this->request->post('img','');
        $title               =     $this->request->post('title','');

        if(empty($notice_id)){
            return jsonError(500,'参数不能为空','');
        }

        $insert = [];
        if($cont){
            $insert['cont'] = $cont;
        }
        if($img){
            $insert['img'] = $img;
        }
        if($title){
            $insert['title'] = $title;
        }

        $res = Db::name('notice')->where(['notice_id' => $notice_id])->update($insert);

        if($res)
        {
            return jsonSuccess(200,'保存成功','');
        }else{
            return jsonError(500,'保存失败','');
        }
    }

    //删除公告
    public function del_notice(){
        $notice_id              =     $this->request->post('type',0);
        $re = Db::name('notice')->where('notice_id',$notice_id)->delete();
        if($re){
            ajaxSuccess('成功');
        }else{
            ajaxError('失败');
        }
    }

    public function edit_neirogn(){
        $notice_id              =     $this->request->get('type',0);

        $re = Db::name('notice')->where('notice_id',$notice_id)->find();

        $this->assign('user', $re);
        return $this->fetch();
    }

    public function edit_neirogn_sub(){
        $notice_id              =     $this->request->post('notice_id',0);
        $cont               =     $_POST['cont'];
        $img               =     $this->request->post('img','');
        $image               =     $this->request->post('image','');
        $title               =     $this->request->post('title','');

        if(empty($notice_id)){
            return jsonError(500,'参数不能为空','');
        }
        if(empty($title)){
            return jsonError(500,'标题不能为空','');
        }


        $insert = [];
        if($cont){
            //$insert['cont'] = htmlspecialchars($cont);
            $insert['cont'] = $cont;
        }
        if($img){
            $insert['img'] = $img;
        }
        if($title){
            $insert['title'] = $title;
        }

        $res = Db::name('notice')->where(['notice_id' => $notice_id])->update($insert);

        if($res)
        {
            return jsonSuccess(200,'保存成功','');
        }else{
            return jsonError(500,'保存失败','');
        }
    }

}

